# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # Controllers from Courses context
    App\Courses\Application\Controllers\:
        resource: '../src/Courses/Application/Controllers/'
        tags: ['controller.service_arguments']

    # Controllers from Users context
    App\Users\Application\Controllers\:
        resource: '../src/Users/Application/Controllers/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Shared\Infrastructure\EventListener\ExceptionListener:
        arguments:
            $logger: '@logger'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    
    App\Shared\Infrastructure\ArgumentResolver\RequestResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 50 }

when@test:
    services:
        App\Tests\:
            resource: '../tests/'
            exclude: '../tests/{bootstrap.php,BaseTestCase.php}'
            autowire: true
            autoconfigure: true
